04-Stacks-And-Queues/03-stacks-and-queues-activity.md
04-Stacks-And-Queues/class-lesson.instructor.md
config.yaml

I would appreciate a review of this sample class lesson for CS Fun in internship.  I have the in class coding exercises here:
- [Reorder Linked Lists](https://replit.com/@adadev/reorderlinkedlist)
- [Daily Temperatures](https://replit.com/@adadev/Daily-Temperatures)
I'm using Replit because it's easier to collaborate (time is essential) and very self-contained.

stacks & queues in-class lesson

---

03-Binary-Search-Trees/02-Binary-Search-Trees.md
03-Binary-Search-Trees/03-Binary-Search-Trees-Height-Big-O.md
03-Binary-Search-Trees/04-Binary-Search-Trees-Traversal.md
03-Binary-Search-Trees/class-lesson.instructor.md

Before: 
- Serialization lesson from C16
- instructor class lesson overview doc from C16
Now:
- Revises C16 serialization for clarity
- Adds BFS pseudocode (class livecode will be BFS walkthrough)
- Adds explanation of Big O for serialization algorithms
- Revises instructor class lesson overview to be up to date with C17 lesson plan
- Updates `TreeNode` class in BST implementation lesson to use `not` for comparison instead of `== None` for code style conventions
For review 
- Clarity of explanation
- Flow and structure
-Lines 267 - 322 of the travesal file are unfinished - should we ask students to implement a `height` function recursively?
- If finished they would be asked to complete a height exercise recursively
- If removed, we would instead provide pseudocode or an example …

Kp/bst traversal Review Third

---

02-linked-lists/01-linked-lists.md

Before:
- Lesson linked to outdated slides and project
Now:
- Slides and project link updated for c17

Update links for c17

---

03-Binary-Search-Trees/07-Binary-Search-Trees-Activity.md

Before:
Activity was a livecode of BST deletion than group work writing a method to find the kth smallest node in the BST.
Now:
Activity is livecode of BFS in a BST
Group work is recursive implementation of DFS algorithms
For review:
Check replit links work
Content accuracy

BFS and DFS activity

---

03-Binary-Search-Trees/02-Binary-Search-Trees.md
03-Binary-Search-Trees/03-Binary-Search-Trees-Height-Big-O.md

The purpose of this PR is to add explanation videos for the BST lesson.

BST Explanation Videos

---

08-graphs/02-graphs-algorithms.md

The purpose of this PR is to add in practice questions for BFS/DFS algorithms.
Previously:
- Pseudocode for each algorithm was described in lieu of challenge question
Currently:
- Added challenge questions for BFS (iterative) and DFS (iterative & recursive)
- Pseudocode moved to the hints of newly created challenge questions
To review:
- Grammar/voice
- Test cases
- Clarity of example implementations

Graph DFS/BFS Problem Set

---

08-graphs/02-graphs-algorithms.md

The purpose of this PR is to add links to the lesson's exercise explanation videos.

Add exercise explanation videos

---

09-graphs-p2/04-graphs-2.checkpoint.md
config.yaml

The purpose of this PR is to add the Minimum Effort Path project to the lesson.
For review:
- Please ensure links are pointing to the intended place

Add project assignment

---

09-graphs-p2/03-graphs-2-activity.md

Update title for Class Activity

---

07-algorithms/03-greedy-algorithms.md

The purpose of this PR is to add a link to the explanation video for the coin change problem.

Add link to coin change video explanation

---

07-algorithms/07-algorithms-activity.md

Summary of changes:
- Multiple choice questions asking students to match interview questions with correct algorithmic approach
- replits to work on interview questions
- Steps to take if students get stuck while in breakout rooms (to address feedback that students get into breakout rooms and don't know what to do)
- Livecode description
Note: replits currently lack README

Add activity

---

07-algorithms/05-sliding-window.md

The purpose of this PR is to add the solution video for the minimum sublist length problem.

embed solution video for minimum sublist

---

07-algorithms/07-algorithms-activity.md

The purpose of this PR is to add an alternative greedy question to the Algorithms activity.

New Greedy Activity Question

---

11-crash-courses/02-recursion.md
config.yaml

The purpose of this PR is to add a crash course for recursion.
One thing I would like to mention is when reviewing the Sorted Array to BST function near the end of the video, I accidentally left out the code while walking through the example 😵‍💫 There's still an example of the code in the slides and I've also provided a link to step through the code in Python Tutor, so hopefully it is still relatively straightforward to follow along in the video.

Recursion Crash Course

---

07-algorithms/03-greedy-algorithms.md

The purpose of this PR is to update the time complexity for the presented solution to the coin change problem. Currently, the time complexity is listed as O(n), however the solution makes use of the python sort() function, which is an O(nlogn) operation. 
For review:
* Please run learn preview to verify the changes 
* Let me know if anything is amiss!

Update time complexity for coin change algorithm

---

00-about-thursdays-at-ada/about-thursdays-at-ada.md

- Adds links from TAA Intro email to About TAA doc

Add Career Services Links

---

01-algorithms/02-algorithm-analysis.md

- Add video walkthrough for Algorithmic Approaches - Algorithmic Analysis lesson

Add analysis of algorithms playlist

---

01-algorithms/03-recursion.md

- Add video walkthrough for written recursion lesson

Add recursion playlist

---

00-about-thursdays-at-ada/about-thursdays-at-ada.md

- Add link to mock interview question bank

Add mock interview questions

---

02-linked-lists/02-linked-lists-oop.md

- Add video lessons
- Add learning objectives
The learning objectives aren't in the video because I added them later, but... oh well

Add video lessons

---

00-study-plan/study-plan.checkpoint.md

**Summary of changes**
- Clarifies wording of study plan submission link
- Changes to 0 point question so that it will not affect students who did not submit a study plan.

Clarify wording of study plan submission question

---

00-about-thursdays-at-ada/about-thursdays-at-ada.md

The purpose of this PR is to update the Panopto link for class recordings to the correct folder. I also removed an erroneous link - we had two that sent folx to the same folder.

Update Panopto Links

---

00-about-thursdays-at-ada/about-thursdays-at-ada.md

Update Link to BST Lesson in About TAA 

---

02-linked-lists/06-linked-list-activity.md
config.yaml

The purpose of this PR is to add the linked list activity replits and instructions to the Linked List lesson.
For review:
* Please run learn preview 
* Double check links navigate to correct place

Add linked list activity

---

03-Binary-Search-Trees/05-Binary-Search-Trees-Activity.md

The purpose of this PR is to add the activity & livecode for the BST lesson.
For review:
* Link correctness
* Proper wording

BST Activity

---

04-graphs/02-representing-graphs.md

- Add video lesson to Representing Graphs Practice

Add video lesson

---

05-dijkstras/03-dijkstra.md

Updates Dijkstra's Time Complexity Explanation 
- Added solution under dropdown for reference
- Annotated the solution for Big O
- Added step-by-step analysis of Big O for sample solution
- Updated adjacency list Big O explanation
- Added callout about Big O when `decrease_key` operation is available

Update time complexity explanation

---

05-dijkstras/02-traversal-review.md

- Add learning goals
- Add video lesson playlist
- Fix headings

Add traversal video

---

05-dijkstras/03-dijkstra.md

- Add Dijkstra's video playlist

Add dijkstra video lessons

---

04-graphs/06-graphs-activity.md

Update the graphs pt.1 lesson with the replit links to the live code and group activities.

Update Graph Activity in Learn

---

04-graphs/03-bfs.md

Update challenge question based on this feedback:
https://adad18.slack.com/archives/C04LL1CJCG6/p1682211894658899
tl;dr The image indicates Portland is a neighbor of Kona

Update Kona's list of neighbors in Q2

---

05-dijkstras/04-dijkstras-activity.md

Fix typo in Dijkstra activity

---

00-about-thursdays-at-ada/about-thursdays-at-ada.md

- update study hall link
- update study hall host key

Update study hall link

---

00-about/norms.md
00-study-plan/study-plan.md
01-algorithms/01-algorithms.md

Changes references to Interview Practice Questions to Problem Solving Exercises. Addresses this ticket: https://app.asana.com/0/home/1202623581143428/1205003469615033

Change references of IPQs to PSEs

---

01-algorithms/09-algorithms-class-discussion.md
02-linked-lists/07-linked-lists-class-discussions.md
03-Binary-Search-Trees/06-Binary-Search-Trees-Class-Discussions.md
04-graphs/07-graphs-class-discussions.md
05-dijkstras/05-dijkstras-class-discussions.md
config.yaml

Added a new tab for each lesson to embed the [Panopto videos](https://adaacademy.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx#folderID=%2285008c14-9981-42fe-8950-afc0016af8e9%22&page=0&maxResults=50) from the C18 class discussions. Addresses this ticket: https://app.asana.com/0/1201700438643002/1205003469615023

Embed Lecture Videos

---

02-linked-lists/01-linked-lists.md
03-Binary-Search-Trees/01-Binary-Search-Trees.md
04-graphs/01-graphs.md
05-dijkstras/03-dijkstra.md

Added explicit callouts to identify each topic's place in industry and/or interview settings.

AP/ Update lessons with explicit use industry use cases

---

01-algorithms/01-algorithms.md
01-algorithms/02-algorithm-analysis.md
01-algorithms/03-recursion.md
01-algorithms/04-algorithms-divide-conquer.md
01-algorithms/05-sliding-window.md
01-algorithms/06-algorithms-dynamic-programming.md
01-algorithms/07-algorithms-supplemental-resources.md

Noticed some typos while reading through last week, so did a typo/formatting pass.

Algorithmic Analysis proof reading pass

---

00-intro/intro.md

The purpose of this PR is to add a link to the PSE feedback request form.

PSE Feedback Form

---

04-graphs/01-graphs.md
04-graphs/03-bfs.md

Asana tickets
- [Typo in adjacency matrix hint](https://app.asana.com/0/1205655776549324/1205771451864009/f)
- I[terative Breadth First Search (BFS) implementation prompt is incorrect](https://app.asana.com/0/1205655776549324/1205789487650313/f)
- [Error in hint markup for BFS challenges ](https://app.asana.com/0/1205655776549324/1205771451864024/f)

Small typo & error fixes for C22

---

01-algorithms/03-recursion.md
01-algorithms/08-algorithms-activity.md
02-linked-lists/06-linked-list-activity.md
03-Binary-Search-Trees/03-Binary-Search-Trees-Traversal.md
03-Binary-Search-Trees/05-Binary-Search-Trees-Activity.md
03-Binary-Search-Trees/class-lesson.instructor.md
04-graphs/07-graphs-activity.md
05-dijkstras/04-dijkstras-activity.md

[Asana Task](https://app.asana.com/0/1205655776549324/1209321695737340)
Remove references to replit & update links to github repos.

Migrate replits to github

---

05-dijkstras/03-dijkstra.md

[Asana Task](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1205941930814365?focus=true)
**Changes**
Update first challenge in 03-dijkstra.md to use a helper function to confirm the results since multiple paths are valid and slightly different implementations may produce different paths.
**Testing**
Confirmed new check with helper function works for the implementation in learn and both alternative implementations in comments on the asana ticket.

Update ambiguous test in Graphs Pt 2/Dijkstra
